export const GET_POSTS = 'POSTS/GET_POSTS';
export const GET_FAVORITES_POSTS = 'POSTS/GET_FAVORITES_POSTS';
export const TOGGLE_FAVORITES = 'POSTS/TOGGLE_FAVORITES';
export const SEARCH_POSTS = 'POSTS/SEARCH_POSTS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_MODAL = 'APP/SHOW_MODAL';
export const HIDE_MODAL = 'APP/HIDE_MODAL';
